moteur2.plugins.workflowsdb.schema = workflowsdb
moteur2.plugins.workflowsdb.connection.username = vip
moteur2.plugins.workflowsdb.connection.password = vipdb
moteur2.plugins.workflowsdb.dialect = org.hibernate.dialect.MySQLDialect
moteur2.plugins.workflowsdb.connection.driver_class = org.mariadb.jdbc.Driver
moteur2.plugins.workflowsdb.connection.url = jdbc:mysql://mariadb:3306/workflowsdb